### ISSUE TITLE
Invalid metric name (HTTP 409 responses)

### ISSUE THREAD

**Issue by aschmid13** [tmcgaughey/epagent-nozzle#2]
We are receiving the following HTTP response on some of the posts to the EPAgent. The other metrics that are successfully posting are very similar format.

> 2016/11/10 13:04:37 Error: EPAgent returned HTTP response: 409 Conflict
2016/11/10 13:04:52 Posting 398 metrics
2016/11/10 13:04:52 Response for 409 Conflict code:
{"errorMessage":"One or more metric specifications were invalid","errorCode":1010,"invalidCount":1,"validCount":397,"metricErrors":[{"metricName":"Firehose:ops:registry_message:","metricErrorCode":1011,"metricErrorMsg":"Invalid metric name","metricErrorIndex":388,"metric":{"type":"LongCounter","name":"Firehose:ops:registry_message:","value":"1"}}]}

**Comment by tmcgaughey** [comment]
I think I see the problem.  I'll be at CA World next week, but will address ASAP.  Thanks!

**Comment by aschmid13** [comment]
Hey Tim, did you have a chance to look into this error?

**Comment by tmcgaughey** [comment]
Yes, but have not stood up the test environment yet.

**Comment by tmcgaughey** [comment]
Merged issue branch.  The Cloud Foundry Nozzle agent is also now part of CA's Digital Experience Insights.
