### ISSUE TITLE
The installation of epagent-nozzle doesn't work anymore

### ISSUE THREAD

**Issue by erboucherie** [tmcgaughey/epagent-nozzle#3]
Since the new version of **noaa** , the installation of **epagent-nozzle** fails with the following error :  
`package github.com/cloudfoundry/noaa/events: cannot find package "github.com/cloudfoundry/noaa/events" in any of:
        /usr/local/go/src/github.com/cloudfoundry/noaa/events (from $GOROOT)
        /home/ubuntu/Workspace/golang/src/github.com/cloudfoundry/noaa/events (from $GOPATH)
`

**Comment by tmcgaughey** [comment]
Merged issue branch.  The Cloud Foundry Nozzle agent is also now part of CA's Digital Experience Insights.
